// Generated by software.model.export_fpga; do not edit manually.
`ifndef GENOME_CLASSIFIER_MODEL_PARAMETERS_SVH
`define GENOME_CLASSIFIER_MODEL_PARAMETERS_SVH

localparam logic signed [31:0] MODEL_BIAS_0 = -32'sd6;
localparam logic signed [31:0] MODEL_BIAS_1 = 32'sd3;
localparam logic signed [31:0] MODEL_BIAS_2 = 32'sd6;
localparam logic signed [31:0] MODEL_BIAS_3 = 32'sd17;
localparam logic signed [31:0] MODEL_OUTPUT_BIAS_ORIGINAL = 32'sd2;
localparam logic signed [31:0] MODEL_OUTPUT_BIAS = -32'sd73;
localparam integer MODEL_QSHIFT = 4;
localparam integer MODEL_ORIGINAL_THRESHOLD = 75;

`endif
